name: Curl Browser Emulation

on:
  push:
    branches:
      - main

jobs:
  make-request:
    strategy:
      matrix:
        go-version: [ 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x ]
        platform: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Curl request to website
        run: |
          curl -X GET "https://www.xxttq.com/?fromuid=141641" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
