name: Curl Browser Emulation

on:
  push:
    branches:
      - main

jobs:
  make-request:
    runs-on: ubuntu-latest

    steps:
      - name: Curl request to website
        run: |
          curl -X GET "https://www.xxttq.com/?fromuid=141600" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
